//⚠️Detalle: rutas ABSOLUTAS ya que ahora se usaran desde 2 html en distintas ubicaciones
export const productos = [
  {
    id: "1",
    nombre: "Harry Potter: El prisionero de Azkaban",
    img: "img/HarryPotterPrisionero.jpg",
    precio: 15,
    categoria: "fantasy",
  },
  {
    id: "2",
    nombre: "Trilogia Mistborn Brandon Sanderson",
    img: "img/Trilogia Misborn.jpg",
    precio: 80,
    categoria: "fantasy",
  },
  {
    id: "3",
    nombre: "El señor de los anillos + El hobbit",
    img: "img/hobbitylotr.jpg",
    precio: 20,
    categoria: "fantasy",
  },
  {
    id: "4",
    nombre: "Trilogia del Archivo de las tormentas",
    img: "img/SandersonArchivo.jpg",
    precio: 20,
    categoria: "fantasy",
  },
  {
    id: "5",
    nombre: "Paquete Agatha Cristie",
    img: "img/AgathaCriestie.jpg",
    precio: 40,
    categoria: "mystery",
  },
  {
    id: "6",
    nombre: "Paquete Percy Jackson",
    img: "img/Percy Jackson.jpg",
    precio: 40,
    categoria: "fantasy",
  },
  {
    id: "7",
    nombre: "El Resplandor",
    img: "img/Resplandor.jpg",
    precio: 60,
    categoria: "fear",
  },
  {
    id: "8",
    nombre: "Colección de Sherlock Holmes",
    img: "img/ColeccionSherlockHolmes.jpg",
    precio: 100,
    categoria: "mystery",
  },
  {
    id: "9",
    nombre: "Orgullo y Prejuicio",
    img: "img/OrgulloPrejuicio.jpg",
    precio: 25,
    categoria: "romance",
  },
];
